/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst } from 'workbox-strategies';
import * as messages from '../types/messages'
import {NetworkError, OsmAdapterApiService, type SessionStatus} from "./server/server";
import * as clients from "./client";
import {OpenPatrolPointsStore, PatrolPointsStore, Patrol as StoredPatrol} from "./store/store";
import type {ScoreDelta} from "../types/model";

declare let self: ServiceWorkerGlobalScope;

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST);
cleanupOutdatedCaches();

// Take control of all clients when activated
self.addEventListener('activate', () => {
    self.clients.claim();
});

// Network-first for API calls
registerRoute(
    ({ url }) => url.pathname.startsWith('/api/'),
    new NetworkFirst({
        cacheName: 'api-cache',
    })
);

/**
 * Listen for messages from clients.
 */
self.addEventListener('message', (event) => {
    const client = event.source as Client;
    const message = event.data as messages.ClientMessage;
    switch (message.type) {
        case 'get-profile':
            getProfile(client);
            break;
        case 'refresh':
            refreshScores(client, message.userId, message.sectionId);
            break;
        case 'submit-scores':
            submitScores(client, message.userId, message.sectionId, message.deltas);
            break;
        default:
            const unrecognized = message as any;
            console.warn(`ServiceWorker: Unexpected message type ${unrecognized.type}`);
    }
});

/**
 * Require the specified user to be logged in.
 * Sends message to client if not logged in.
 * @param server
 * @param client
 * @param userId
 */
async function requireLoggedInUser(server: OsmAdapterApiService, client: Client, userId: number): Promise<SessionStatus>  {
    const session = await server.fetchSession();
    if(!session.isAuthenticated) {
        client.postMessage(messages.newAuthenticationRequiredMessage(server.getLoginUrl()));
        return session;
    }
    if (session.userId != userId) {
        client.postMessage(messages.newWrongUserMessage(userId, session.userId));
        return {isAuthenticated: false };
    }
    return session;
}

/**
 * Fetch the user profile from the server and send it to the client.
 * If the user is logged in, then a UserProfileMessage is given.
 * If the user is logged out, then an AuthenticationRequiredMessage is given.
 *
 * All clients will receive a SectionListChangeMessage if the section list has
 * changed. This is published after the UserProfileMessage sent to the calling
 * client. The first client will expect both messages because its call will
 * initialize the section list for the first time. The section list is
 * stored in browser storage until explicitly cleared. * @param client
 */
export async function getProfile(client: Client) {
    const server = new OsmAdapterApiService();
    const session = await server.fetchSession();
    if(!session.isAuthenticated) {
        client.postMessage(messages.newAuthenticationRequiredMessage(server.getLoginUrl()));
        return session;
    }

    const store = await OpenPatrolPointsStore(session.userId);
    try {
        const sections = await server.fetchSections()
        const changed = await store.setCanonicalSectionList(sections);
        client.postMessage(messages.newUserProfileMessage(session.userId, session.userName, sections));
        if (changed) {
            await clients.sendMessage(messages.newSectionListChangeMessage(sections));
        }
    } finally {
        store.close();
    }
}

/**
 * Refresh the scores for the specified section from the server.
 * This synchronizes the canonical list of patrols with the server's list and adjusts the
 * committed score values.
 * @param client
 * @param userId
 * @param sectionId
 */
export async function refreshScores(client: Client, userId: number, sectionId: number) {
    const server = new OsmAdapterApiService();
    const session = await requireLoggedInUser(server, client, userId);
    if(!session.isAuthenticated) {
        return;
    }

    const store = await OpenPatrolPointsStore(userId);
    try {
        const scores = await server.fetchScores(sectionId);
        const newScores = await store.setCanonicalPatrolList(sectionId, scores);
        await clients.publishScores(userId, sectionId, newScores);
    } finally {
        store.close();
    }
}

/**
 * Add pending score changes to the store and trigger a sync.
 * This is called when the user makes changes in the UI.
 */
export async function submitScores(client: Client, userId: number, sectionId: number, deltas: ScoreDelta[]) {
    const store: PatrolPointsStore = await OpenPatrolPointsStore(userId);
    try {
        // Add pending changes to the store.
        // This optimistic update ensures that user intent is saved even if they have lost
        // authentication. This allows the user to recover by logging in again.
        for (const delta of deltas) {
            await store.addPendingPoints(sectionId, delta.patrolId, delta.score);
        }

        // Publish the optimistic update immediately to all clients
        const updatedScores = await store.getScoresForSection(sectionId);
        await clients.publishScores(userId, sectionId, updatedScores);

        // Only perform the sync if the user is still logged in.
        // If the user is not logged in, then requireLoggedInUser will send a message to the client
        // requesting them to log in again.
        const server = new OsmAdapterApiService();
        if (! (await requireLoggedInUser(server, client, userId)).isAuthenticated) {
            return;
        }

        // Perform a sync process for this {user,section} to commit the changes to the server.
        if(!server.isOffline()) {
            await syncPendingScores(server, store, userId, sectionId);
        }
    } finally {
        store.close();
    }
}

/**
 * Sync all pending score changes for a {user,section} to the server.
 * The server and store must be tied to the same user.
 */
async function syncPendingScores(server: OsmAdapterApiService, store: PatrolPointsStore, userId: number, sectionId: number) {
    // Atomically acquire lock and get pending patrols
    let lockId: string | null = null;
    let hasChanges: boolean = false;
    try {
        const {lockId: acquiredLockId, pending} = await store.acquirePendingForSync(sectionId, 30000);
        lockId = acquiredLockId;

        if (pending.length === 0) {
            console.log(`[ServiceWorker] No pending scores to sync for section ${sectionId}`);
            return // via finally;
        }

        // Build the updates array from the pending patrols
        const updates = pending.map((patrol : StoredPatrol):ScoreDelta => ({
            patrolId: patrol.patrolId,
            score: patrol.pendingScoreDelta
        }));
        hasChanges = true;

        console.log(`[ServiceWorker] Syncing ${updates.length} pending scores for section ${sectionId}`);

        // Submit to server
        const serverResult = await server.updateScores(sectionId, updates);

        // Build a unit of work to process all results atomically
        const uow = store.newUnitOfWork();
        for (const patrol of serverResult) {
            if (patrol.success) {
                uow.setCommittedScore(sectionId, patrol.id, patrol.newScore, patrol.name);
                continue;
            }

            // Type narrow: patrol is now a failure result (use type assertion as workaround)
            const failedPatrol = patrol as any;
            if (failedPatrol.isTemporaryError && failedPatrol.retryAfter) {
                // Temporary error - schedule retry
                const retryDate = new Date(failedPatrol.retryAfter);
                uow.setRetryAfter(sectionId, failedPatrol.id, retryDate, failedPatrol.errorMessage);
            } else {
                // Permanent error - mark as failed
                uow.setError(sectionId, failedPatrol.id, failedPatrol.errorMessage || 'Update failed');
            }
        }
        await uow.commit();
    } catch (e: any) {
        // Catastrophic error (network failure, server error, etc.)
        if(e instanceof NetworkError) {
            console.warn(`[ServiceWorker] Network error syncing scores for section ${sectionId}:`, e.cause);
        } else {
            // Mark all pending entries as failed so the user can see what happened
            await store.markAllPendingAsFailed(sectionId, e.message || 'Failed to sync scores');
            console.error(`[ServiceWorker] Error in syncPendingScores for section ${sectionId}:`, e);
        }
    } finally {
        // Always release the lock
        if (lockId) {
            await store.releaseSyncLock(sectionId, lockId);
        }

        // If I did anything, then publish the updated scores to all clients
        if (hasChanges) {
            const updatedScores = await store.getScoresForSection(sectionId);
            await clients.publishScores(userId, sectionId, updatedScores);
        }
    }
}
